
[package]
name = 'cyfs-dsg-client'
version = '0.6.6'
edition = '2021'
license = 'BSD-2-Clause'
description = 'Rust dsg-client package'

[dependencies]
async-std = { version = '1.8', features = ['std'] }
async-trait = '0.1.53'
async-recursion = '1.0.0'
log = '0.4'
protobuf = { version = '2', features = ['with-bytes'] }
serde = { version = '1.0', features = ['derive'] }
serde_json = '1.0'
sha2 = '0.8.1'
generic-array = { version = '0.12', default-features = false, features = ['serde'] }
aes = '=0.7'
block-modes = '=0.8'
rand = '0.8.5'
cyfs-base = "0.6"
cyfs-lib = "0.8"
cyfs-util = "0.6"
cyfs-debug = "0.6"
cyfs-core = "0.6"
cyfs-bdt = "0.6"
cyfs-chunk-lib = "0.6"
tracing = { version = "0.1", features = ["log-always"]}

[build-dependencies]
protoc-rust = '2'
protoc-bin-vendored = '3'
